### ISSUE TITLE
Failed build on linux version 2.0.0

### ISSUE THREAD

**Issue by myslajek** [unitedideasco/system_idle#20]
Hi,
I have a problem to build project on Linux (Ubuntu) with version 2.0.0. Build working with 1.0.0. There is an error occurred during build:
`project_folder/linux/flutter/ephemeral/.plugin_symlinks/system_idle_linux/src/wayland-ext_idle_notify_v1.h:159:105: error: use of undeclared identifier 'WL_MARSHAL_FLAG_DESTROY'
project_folder/linux/flutter/ephemeral/.plugin_symlinks/system_idle_linux/src/wayland-ext_idle_notify_v1.h:179:7: error: use of undeclared identifier 'wl_proxy_marshal_flags'
project_folder/linux/flutter/ephemeral/.plugin_symlinks/system_idle_linux/src/wayland-ext_idle_notify_v1.h:270:113: error: use of undeclared identifier 'WL_MARSHAL_FLAG_DESTROY'
`.

My flutter i tried to build on Flutter version 3.24.4 and on the latest 3.29.0 and still not working.
